[workspace]
members = [
    "program",
    "verifier",
]
resolver = "2"

[workspace.package]
authors = ["Joe Caulfield <jcaulfield135@gmail.com>"]
repository = "https://github.com/buffalojoec/invoke"
license = "Apache-2.0"
edition = "2021"

[workspace.dependencies]
mollusk-svm = "0.0.1"
num-traits = "0.2"
solana-program = "2.0.11"
solana-sdk = "2.0.11"
spl-program-error = "0.5.0"
thiserror = "1.0.64"
